// Default values for all `Frame` fields.
//
// Extracted from `frame.rs` to keep file sizes manageable. The macro is
// used by `impl Default for Frame` and must stay in sync with the struct
// definition in `frame.rs`.

/// Build a `Frame` with all defaults. `$id` is the expression for the `id` field.
macro_rules! frame_defaults {
    ($id:expr) => {
        Frame {
            id: $id,
            widget_type: WidgetType::Frame,
            object_type_name: None,
            name: None,
            parent_id: None,
            children: Vec::new(),
            width: 0.0,
            width_is_text_auto: false,
            height: 0.0,
            height_is_text_auto: false,
            anchors: Vec::new(),
            xml_set_all_points: false,
            visible: true,
            show_hide_depth: 0,
            click_depth: 0,
            collapses_layout: false,
            registered_events: HashSet::new(),
            registered_unit_events: HashMap::new(),
            frame_level: 0,
            raise_order: 0,
            has_fixed_frame_level: false,
            frame_level_offset: None,
            uses_parent_level: false,
            frame_strata: FrameStrata::Medium,
            has_fixed_frame_strata: false,
            flattens_render_layers: false,
            toplevel: false,
            alpha: 1.0,
            ignore_parent_alpha: false,
            effective_alpha: 1.0,
            anim_offset_x: 0.0,
            anim_offset_y: 0.0,
            scale: 1.0,
            ignore_parent_scale: false,
            effective_scale: 1.0,
            mouse_enabled: false,
            mouse_wheel_enabled: false,
            motion_scripts_while_disabled: false,
            gamepad_button_enabled: false,
            gamepad_stick_enabled: false,
            propagate_mouse_clicks: false,
            propagate_mouse_motion: false,
            propagate_hyperlinks_to_parent: false,
            pass_through_buttons: HashSet::new(),
            hit_rect_insets: (0.0, 0.0, 0.0, 0.0),
            clamp_rect_insets: (0.0, 0.0, 0.0, 0.0),
            keyboard_enabled: false,
            propagate_keyboard_input: false,
            texture: None,
            texture_file_data_id: None,
            color_texture: None,
            vertex_color: None,
            gradient: None,
            alpha_gradients: HashMap::new(),
            text: None,
            text_stripped: None,
            text_segments: Vec::new(),
            title: None,
            text_color: Color::new(1.0, 0.8, 0.2, 1.0),
            text_color_fixed: false,
            shadow_color: Color::new(0.0, 0.0, 0.0, 0.0),
            shadow_offset: (0.0, 0.0),
            font: None,
            font_size: 14.0,
            font_outline: TextOutline::None,
            justify_h: TextJustify::Center,
            justify_v: TextJustify::Center,
            attributes: HashMap::new(),
            backdrop: Backdrop::default(),
            children_keys: HashMap::new(),
            parent_key: None,
            movable: false,
            resizable: false,
            resize_bounds_min: (0.0, 0.0),
            resize_bounds_max: None,
            user_placed: false,
            dont_save_position: false,
            registered_mouse_buttons: HashSet::new(),
            registered_click_buttons: HashSet::new(),
            registered_drag_buttons: HashSet::new(),
            highlight_locked: false,
            ignoring_children_for_bounds: false,
            clamped_to_screen: false,
            is_moving: false,
            is_sizing: false,
            sizing_point: crate::widget::AnchorPoint::BottomRight,
            word_wrap: true,
            max_lines: 0,
            text_scale: 1.0,
            normal_texture: None,
            normal_tex_coords: None,
            pushed_texture: None,
            pushed_tex_coords: None,
            highlight_texture: None,
            highlight_tex_coords: None,
            disabled_texture: None,
            disabled_tex_coords: None,
            checked_texture: None,
            checked_tex_coords: None,
            disabled_checked_texture: None,
            disabled_checked_tex_coords: None,
            left_texture: None,
            middle_texture: None,
            right_texture: None,
            draw_layer: DrawLayer::Artwork,
            draw_sub_layer: 0,
            region_order: next_region_order(),
            disabled_draw_layers: BTreeSet::new(),
            horiz_tile: false,
            vert_tile: false,
            tex_coords: None,
            tex_coords_quad: None,
            atlas_tex_coords: None,
            atlas: None,
            nine_slice_layout: None,
            nine_slice_atlas: None,
            three_slice_h: None,
            alpha_mode: None,
            blend_mode: BlendMode::Alpha,
            snap_to_pixel_grid: false,
            texel_snapping_bias: 0.0,
            texture_slice_margins: (0.0, 0.0, 0.0, 0.0),
            texture_slice_mode: 0,
            register_all_events: false,
            clips_children: false,
            is_frame_buffer: false,
            minimap_blip_texture: None,
            fog_of_war_background_atlas: None,
            fog_of_war_mask_atlas: None,
            fog_of_war_mask_scalar: None,
            fog_of_war_ui_map_id: None,
            minimap_mask_texture: None,
            minimap_icon_texture: None,
            minimap_player_texture: None,
            minimap_poi_arrow_texture: None,
            minimap_corpse_poi_arrow_texture: None,
            minimap_static_poi_arrow_texture: None,
            minimap_ping_position: None,
            minimap_blip_update_revision: 0,
            quest_blob_inside: MinimapBlobLayerStyle::default(),
            quest_blob_outside: MinimapBlobLayerStyle::default(),
            quest_blob_ring: MinimapBlobRingStyle::default(),
            task_blob_inside: MinimapBlobLayerStyle::default(),
            task_blob_outside: MinimapBlobLayerStyle::default(),
            task_blob_ring: MinimapBlobRingStyle::default(),
            arch_blob_inside: MinimapBlobLayerStyle::default(),
            arch_blob_outside: MinimapBlobLayerStyle::default(),
            arch_blob_ring: MinimapBlobRingStyle::default(),
            is_mask: false,
            mask_textures: Vec::new(),
            rotation: 0.0,
            model_state: None,
            mouse_motion_enabled: false,
            user_id: 0,
            button_state: 0,
            pushed_text_offset: (0.0, 0.0),
            layout_rect: None,

            // Slider
            slider_value: 0.0,
            slider_min: 0.0,
            slider_max: 100.0,
            slider_step: 1.0,
            slider_orientation: "HORIZONTAL".to_string(),
            slider_obey_step_on_drag: false,
            slider_steps_per_page: 1,
            slider_scroll_percentage: 0.0,
            slider_visible_extent_percentage: 0.0,
            slider_pan_extent_percentage: 0.0,

            // StatusBar
            statusbar_value: 0.0,
            statusbar_min: 0.0,
            statusbar_max: 1.0,
            statusbar_interpolated_value: 0.0,
            statusbar_interpolation_target: None,
            statusbar_color: None,
            statusbar_texture_path: None,
            statusbar_bar_id: None,
            statusbar_desaturation: 0.0,
            statusbar_fill_style: "STANDARD".to_string(),
            statusbar_reverse_fill: false,
            statusbar_orientation: "HORIZONTAL".to_string(),

            // EditBox
            editbox_cursor_pos: 0,
            editbox_max_letters: 0,
            editbox_max_bytes: 0,
            editbox_multi_line: false,
            editbox_auto_focus: false,
            editbox_numeric: false,
            editbox_password: false,
            editbox_blink_speed: 0.5,
            editbox_history: Vec::new(),
            editbox_history_max: 0,
            editbox_text_insets: (0.0, 0.0, 0.0, 0.0),
            text_line_spacing: 0.0,
            editbox_count_invisible_letters: false,
            editbox_in_ime_composition_mode: false,
            editbox_alphabetic_only: false,
            editbox_alt_arrow_key_mode: false,
            editbox_numeric_full_range: false,
            editbox_secure_text: false,
            editbox_security_disable_set_text: false,
            editbox_security_disable_paste: false,
            editbox_visible_text_byte_limit: 0,
            editbox_input_language: "ROMAN".to_string(),
            editbox_highlight_range: None,
            editbox_highlight_color: Color::new(1.0, 1.0, 1.0, 1.0),
            editbox_focused: false,

            // ScrollFrame
            scroll_child_id: None,
            scroll_child_rect_size: None,
            scroll_horizontal: 0.0,
            scroll_vertical: 0.0,

            // Cooldown
            cooldown_start: 0.0,
            cooldown_duration: 0.0,
            cooldown_reverse: false,
            cooldown_draw_swipe: true,
            cooldown_draw_edge: false,
            cooldown_draw_bling: true,
            cooldown_hide_countdown: false,
            cooldown_swipe_texture: None,
            cooldown_edge_texture: None,
            cooldown_bling_texture: None,
            cooldown_display_duration_ms: 0.0,
            cooldown_mod_rate: 1.0,
            cooldown_edge_scale: 1.0,
            cooldown_use_circular_edge: false,
            cooldown_countdown_abbrev_threshold_seconds: 0.0,
            cooldown_min_countdown_duration_ms: 0.0,
            cooldown_use_aura_display_time: false,
            cooldown_edge_color: Color::rgb(1.0, 1.0, 1.0),
            cooldown_tex_coord_range: None,
            cooldown_countdown_font_string_id: None,
            cooldown_paused: false,

            // Line
            line_start: None,
            line_end: None,
            line_thickness: 1.0,

            // Rendering effects
            desaturated: false,

            // Profiler
            owner_addon: None,

            default_parent: false,
            forbidden: false,
            is_protected: false,
            prevent_secret_values: false,
            tooltip_owner_id: None,
            blocking_loads_requested: false,
            vertex_offsets: None,
        }
    };
}
