use super::*;

pub struct SimState {
    pub widgets: WidgetRegistry,
    pub events: EventQueue,
    pub scripts: ScriptRegistry,
    pub console_output: Vec<String>,
    pub timers: VecDeque<PendingTimer>,
    pub rilua_timers: VecDeque<crate::lua_api::timer_layout::RiluaPendingTimer>,
    pub focused_frame_id: Option<u64>,
    pub addons: Vec<AddonInfo>,
    pub addon_saved_enable_state: Option<AddonEnableSnapshot>,
    pub addon_saved_version_check_enabled: Option<bool>,
    pub system_chat_log: Vec<String>,
    pub adventure_map: AdventureMapState,
    pub encounter_journal: EncounterJournalState,
    pub anima_diversion: AnimaDiversionState,
    pub garrison_talents: GarrisonTalentState,
    pub clipboard: ClipboardState,
    pub chat_edit_open_state: Option<ChatEditOpenState>,
    pub quest_portrait_state: Option<QuestPortraitState>,
    pub cvars: CVarStorage,
    pub tooltips: HashMap<u64, TooltipData>,
    pub blocked_auras_by_unit: HashMap<String, HashSet<i32>>,
    pub quest_blobs: HashMap<u64, QuestBlobState>,
    pub fog_of_war_frames: HashMap<u64, FogOfWarFrameState>,
    pub unit_position_frames: HashMap<u64, UnitPositionFrameState>,
    pub pending_player_reports: HashMap<i64, PendingPlayerReport>,
    pub simple_htmls: HashMap<u64, SimpleHtmlData>,
    pub message_frames: HashMap<u64, MessageFrameData>,
    pub on_update_frames: HashSet<u64>,
    pub visible_on_update_cache: Option<Vec<u64>>,
    pub strata_buckets: Option<Vec<Vec<u64>>>,
    pub(crate) active_toplevel_show_orders: HashMap<u64, u64>,
    pub(crate) next_toplevel_show_order: u64,
    pub pending_hit_grid_changes: Vec<(u64, bool)>,
    pub pending_texture_preloads: BTreeSet<String>,
    pub animation_groups: HashMap<u64, AnimGroupState>,
    pub active_animation_groups: HashSet<u64>,
    pub next_anim_group_id: u64,
    pub anim_frame_to_group: HashMap<u64, u64>,
    pub anim_frame_to_anim: HashMap<u64, (u64, usize)>,
    pub screen_width: f32,
    pub screen_height: f32,
    pub screen_kind: ScreenKind,
    pub is_logged_in: bool,
    pub post_event_workarounds_applied: bool,
    pub screen_first_displayed: bool,
    pub saved_account_name: String,
    pub saved_account_list: String,
    pub uses_token: bool,
    pub account_save_enabled: bool,
    pub account_save_in_progress: bool,
    pub account_locked_post_save: bool,
    pub last_account_store_purchase_request: Option<i64>,
    pub account_store_begin_purchase_succeeds: bool,
    pub last_account_store_refund_request: Option<i64>,
    pub account_store_refund_succeeds: bool,
    pub account_store_category_items: HashMap<i64, Vec<i64>>,
    pub account_store_currency_for_store: HashMap<i64, i64>,
    pub account_store_currency_info: HashMap<i64, AccountStoreCurrencyInfo>,
    pub account_store_storefront_state: HashMap<i64, i64>,
    pub last_account_store_storefront_info_request: Option<i64>,
    pub account_store_categories: HashMap<i64, AccountStoreCategoryInfo>,
    pub account_store_items: HashMap<i64, AccountStoreItemInfo>,
    pub action_bars: HashMap<u32, u32>,
    pub action_outfits: HashMap<u32, i64>,
    pub equipped_gear_outfit_action_slots: HashSet<u32>,
    pub assisted_combat: AssistedCombatState,
    pub action_bar_page: u32,
    pub has_override_action_bar: bool,
    pub has_vehicle_action_bar: bool,
    pub vehicle_bar_index: i32,
    pub override_bar_skin: Option<i32>,
    pub override_bar_index: i32,
    pub has_temp_shapeshift_action_bar: bool,
    pub temp_shapeshift_bar_index: i32,
    pub has_bonus_action_bar: bool,
    pub bonus_bar_index: i32,
    pub action_bar_state: ActionBarStateInfo,
    pub action_highlights: ActionHighlightState,
    pub extra_action_button: ExtraActionButtonState,
    pub equipped_artifact: Option<ArtifactInfo>,
    pub artifact_point_costs: HashMap<(i32, i32), i64>,
    pub allied_races: HashMap<i64, AlliedRaceInfo>,
    pub model_scenes: HashMap<i64, Vec<String>>,
    pub active_player_interactions: HashSet<i32>,
    pub azerite_item: Option<AzeriteItemState>,
    pub azerite_essence: AzeriteEssenceState,
    pub azerite_empowered: AzeriteEmpoweredItemState,
    pub barber_shop: BarberShopState,
    pub major_factions: HashMap<i64, MajorFactionData>,
    pub major_faction_renown_levels: HashMap<i64, Vec<RenownLevelInfo>>,
    pub account_wide_reputation_factions: HashSet<i64>,
    pub faction_paragon: HashMap<i64, FactionParagonInfo>,
    pub transmog_outfit_locks: HashSet<i64>,
    pub equipped_outfit_locked: bool,
    pub locked_action_slots: HashSet<i32>,
    pub is_active_battlefield: bool,
    pub spell_trade_skill_links: HashMap<u32, String>,
    pub spell_id_aliases: HashMap<String, u32>,
    pub spell_loss_of_control: HashMap<u32, LossOfControlInfo>,
    pub spell_flyouts: HashMap<u32, SpellFlyoutInfo>,
    pub action_profession_quality: HashMap<i32, ProfessionQualityInfo>,
    pub addon_base_paths: Vec<PathBuf>,
    pub create_frame_initial_hidden: Option<bool>,
    pub suppress_runtime_on_load_depth: u32,
    pub xml_load_addon_depth: u32,
    pub mouse_position: Option<(f32, f32)>,
    pub hovered_frame: Option<u64>,
    pub active_drag_frame: Option<u64>,
    pub active_slider_thumb_drag_frame: Option<u64>,
    pub next_report_token: i64,
    pub party_members: Vec<PartyMember>,
    pub party_group_active: bool,
    pub current_target: Option<TargetInfo>,
    pub previous_target: Option<TargetInfo>,
    pub current_focus: Option<TargetInfo>,
    pub enemy_pool: Vec<TargetInfo>,
    pub sound_manager: Option<SoundManager>,
    pub last_sound_kit_requested: Option<u32>,
    pub last_sound_file_requested: Option<String>,
    pub last_stopped_sound_handle: Option<u32>,
    pub last_launched_url: Option<String>,
    pub highlighted_map_scene_character_guid: Option<String>,
    pub secure_attribute_drivers: HashMap<u64, HashMap<String, String>>,
    pub rot_damage_level: usize,
    pub fps: f32,
    pub start_time: Instant,
    pub casting: Option<CastingState>,
    pub channeling: Option<CastingState>,
    pub next_cast_id: u32,
    pub gcd: Option<(f64, f64)>,
    pub spell_cooldowns: HashMap<u32, SpellCooldownState>,
    pub inventory_item_cooldowns: HashMap<i32, SpellCooldownState>,
    pub action_ui_buttons: Vec<(u64, u32)>,
    pub cursor_item: Option<CursorInfo>,
    pub loading_addon_index: Option<u16>,
    pub loading_addon_stack: Vec<u16>,
    pub executing_addon_index: Option<u16>,
    pub loading_nil_symbol_environment: Option<NilSymbolEnvironment>,
    pub loading_forbidden: bool,
    pub loading_scoped_script_env: Option<rilua::Val>,
    pub loading_add_to_secure_env: bool,
    pub loading_hide_from_global_env: bool,
    pub loading_use_forbidden_object_table: bool,
    pub app_frame_metrics: AppFrameMetrics,
    pub addon_performance_messages_shown: HashSet<AddonPerformanceMessageKey>,
    pub talents: crate::lua_api::talent_state::TalentState,
    pub lua_errors: Vec<String>,
    pub lua_error_records: Vec<LuaErrorRecord>,
    pub lua_error_counts: HashMap<String, usize>,
    pub nil_symbol_accesses: Vec<NilSymbolAccess>,
    pub global_publications: HashSet<(u16, String)>,
    pub secure_global_publications: HashSet<(u16, String)>,
    pub pending_nested_addon_diagnostics: HashMap<u16, LoadDiagnostics>,
    pub runtime_addon_diagnostics: LoadDiagnostics,
    pub global_show_hide_depth: u32,
    pub anim_sync_times: HashMap<String, std::time::Duration>,

    pub player: PlayerState,
    pub player_xp: PlayerXpState,
    pub bind_location: String,
    pub pvp_honor: PvpHonorState,
    pub world: WorldState,
    pub bag_items: HashMap<(i32, i32), BagItem>,
    pub tracked_recipes: TrackedRecipes,
    pub crafting: CraftingState,
    pub net_stats: NetStats,
    pub store_frame_shown: bool,
    pub timerunning_season_id: Option<u32>,
    pub timerunning_season_seconds_remaining: u64,
    pub modifier_keys: ModifierKeys,
    pub mouse_buttons: MouseButtons,
    pub game_rules: GameRulesState,
    pub discord: DiscordState,
    pub player_choice: PlayerChoiceState,
    pub housing_service_enabled: bool,
    pub housing: HousingState,
    pub pet_battles: PetBattleState,
    pub pet: PetState,
    pub lfg_list_counts: LfgListCounts,
    pub can_use_premade_group: bool,
    pub lfg_category_info: std::collections::HashMap<i32, LfgCategoryInfo>,
    pub lfg_active_categories: std::collections::HashSet<i32>,
    pub lfg_queued_dungeons: std::collections::HashMap<i32, std::collections::BTreeSet<i32>>,
    pub lfg_queue_pop_delay_seconds: f64,
    pub lfg_queue_pop_due_at: Option<Instant>,
    pub lfg_active_proposal: Option<LfgProposalState>,
    pub lfg_random_cooldown_units: std::collections::HashSet<String>,
    pub lfg_activity_groups: Vec<LfgActivityGroupInfo>,
    pub lfg_activities: Vec<LfgActivityInfo>,
    pub lfg_applications: Vec<LfgApplication>,
    pub lfg_next_application_id: u64,
    pub lfg_advanced_filter: LfgAdvancedFilter,
    pub lfg_language_filter: std::collections::HashMap<String, bool>,
    pub lfg_roles: LfgRoleSelection,
    pub lfd_dungeons: Vec<LfdDungeonInfo>,
    pub lfd_enabled_dungeons: std::collections::HashMap<i32, bool>,
    pub photo_sharing_authorized: bool,
    pub photo_sharing_enabled: bool,
    pub tutorial_flags: HashSet<u32>,
    pub wowlabs: WowLabsState,
    pub archaeology: ArchaeologyState,
    pub arrow_callouts: ArrowCalloutState,
    pub gardenweald: GardenwealdState,
    pub viewed_artifact: ViewedArtifactState,
    pub relic_forge_at_forge: bool,
    pub artifact_relic_items: HashSet<i32>,
    pub quest_log: Vec<u32>,
    pub quest_log_entries: QuestLogState,
    pub pending_quest_offer: Option<u32>,
    pub quest_choice_id: Option<u32>,
    pub quest_choice_response_id: Option<u32>,
    pub quest_poi_map_id: Option<i32>,
    pub selected_quest_log_id: Option<u32>,
    pub abandon_quest_id: Option<u32>,
    pub tracked_achievements: HashSet<i32>,
    pub bank_frame_open: bool,
    pub guild_bank_frame_open: bool,
    pub bank_purchased_slots: i32,
    pub guild_bank_money: i64,
    pub current_guild_bank_tab: i32,
    pub guild_bank_items: HashMap<(i32, i32), BagItem>,
    pub merchant_frame_open: bool,
    pub tabard_frame_open: bool,
    pub trainer_frame_open: bool,
    pub socket_frame_open: bool,
    pub loot_frame_open: bool,
    pub guild_registrar_open: bool,
    pub pet_stables_open: bool,
    pub merchant_items: Vec<u32>,
    pub loot_slots: Vec<BagItem>,
    pub last_loot_roll_choice: Option<i32>,
    pub auction_browse_items: Vec<u32>,
    pub loot_method: LootMethodState,
    pub loot_history: LootHistoryState,
    pub gossip: GossipState,
    pub torghast: TorghastState,
    pub titles: Vec<String>,
    pub current_title: i32,
    pub shapeshift_forms: Vec<ShapeshiftForm>,
    pub shapeshift_cooldowns: HashMap<i32, SpellCooldownState>,
    pub pet_actions: Vec<PetActionSlot>,
    pub glyph: GlyphState,
    pub currency_info: HashMap<i32, CurrencyInfo>,
    pub equipment_manager: EquipmentManagerState,
    pub maps: HashMap<i32, MapData>,
    pub achievements: HashMap<i32, AchievementInfo>,
    pub achievement_guild_rep: HashMap<i32, AchievementGuildRep>,
    pub achievement_statistics: HashMap<i32, AchievementStatistic>,
    pub achievement_comparison_unit: Option<String>,
    pub achievement_comparison_data: AchievementComparisonData,
    pub guild_achievement_members: HashMap<i32, Vec<String>>,
    pub achievement_search: AchievementSearchState,
    pub focused_achievement: Option<i32>,
    pub area_pois: HashMap<i32, AreaPoiInfo>,
    pub bnet_friends: Vec<BnetFriend>,
    pub bnet_friend_invites: Vec<BnetFriendInvite>,
    pub bnet_appear_offline: bool,
    pub social_friends: Vec<SocialFriend>,
    pub auction_browse_results: Vec<AuctionBrowseResult>,
    pub auction_replicate_items: Vec<AuctionReplicateItem>,
    pub auction_owned: Vec<OwnedAuction>,
    pub auction_bids: Vec<BidAuction>,
    pub auction_item_searches: ::std::collections::HashMap<ItemSearchKey, ItemSearchResults>,
    pub auction_commodity_searches: ::std::collections::HashMap<i32, CommoditySearchResults>,
    pub auction_sell_search_results: ::std::collections::HashMap<ItemSearchKey, ItemSearchResults>,
    pub auction_last_browse_query: Option<BrowseQuery>,
    pub auction_queued_browse_query: Option<BrowseQuery>,
    pub auction_favorites: Vec<ItemSearchKey>,
    pub auction_sell_quote: Option<AuctionSellQuote>,
    pub auction_sell_item: Option<BagItem>,
    pub selected_auction_list: i32,
    pub selected_auction_bidder: i32,
    pub selected_auction_owner: i32,
    pub auction_index: HashMap<i64, AuctionRowInfo>,
    pub commodity_purchase_quote: Option<CommodityPurchaseQuote>,
    pub auction_throttle_ready: bool,
    pub auction_should_auto_populate_price: bool,
    pub wow_token: WowTokenState,
    pub mythic_plus: MythicPlusState,
    pub character_services: CharacterServicesState,
    pub scenario: ScenarioState,
    pub death_recaps: Vec<DeathRecapEntry>,
    pub chat_bubbles: Vec<ChatBubble>,
    pub summon_request: SummonRequestState,
    pub player_map_position: (f64, f64),
    pub factions: Vec<FactionEntry>,
    pub selected_faction_index: i32,
    pub watched_faction_index: i32,
    pub battlefield_queue: BattlefieldQueue,
    pub battlefield_minimap_visible: bool,
    pub chat_channels: Vec<ChatChannel>,
    pub macros: Vec<MacroInfo>,
    pub running_macro: Option<u32>,
    pub chat_windows: ::std::collections::HashMap<i32, ChatWindow>,
    pub chat_type_colors: ::std::collections::HashMap<String, (f32, f32, f32)>,
    pub pending_duel: Option<String>,
    pub pending_resurrect: Option<String>,
    pub corpse_available: bool,
    pub active_trade: Option<TradeState>,
    pub open_panels: ::std::collections::HashSet<String>,
    pub is_party_lfg: bool,
    pub everyone_assistant: bool,
    pub party_leader_index: Option<usize>,
    pub ready_check: ReadyCheckState,
    pub voice_chat: VoiceChatState,
    pub known_spells: ::std::collections::HashSet<u32>,
    pub harmful_spells: ::std::collections::HashSet<u32>,
    pub helpful_spells: ::std::collections::HashSet<u32>,
    pub pet_spells: ::std::collections::HashSet<u32>,
    pub pvp_last_honor_gain: i32,
    pub equippable_items: ::std::collections::HashSet<u32>,
    pub consumable_items: ::std::collections::HashSet<u32>,
    pub can_replace_guild_master: bool,
    pub auto_decline_guild_invites: bool,
    pub guild_roster_show_offline: bool,
    pub menu_open: bool,
    pub xp_disabled: bool,
    pub can_teleport: bool,
    pub has_hearthstone: bool,
    pub message_log: Vec<MessageLogEntry>,
    pub keybindings: Keybindings,
    pub debug_borders: bool,
    pub debug_anchors: bool,
    pub simulator_exit_requested: bool,
}
