use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use quote::ToTokens;
use syn::{
    FnArg, Item, ItemFn, ItemMacro, MacroDelimiter, Pat, PathArguments, ReturnType, Type,
    Visibility,
};

fn main() {
    println!("cargo:rerun-if-changed=installer/wow-sim.ico");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=tests");

    generate_integration_test_harness();
    generate_prefork_full_ui_registry();

    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    if target_os != "windows" {
        return;
    }

    let mut res = winresource::WindowsResource::new();
    res.set_icon("installer/wow-sim.ico");
    if let Err(error) = res.compile() {
        // On hosts without a usable resource compiler the binary should still
        // link; surface the failure as a cargo warning instead of aborting.
        println!("cargo:warning=failed to embed Windows icon resource: {error}");
    }
}

fn generate_integration_test_harness() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let tests_dir = manifest_dir.join("tests");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("out dir"));
    let harness_path = out_dir.join("integration_tests.rs");

    let mut module_files = discover_top_level_test_modules(&tests_dir);
    module_files.sort();

    let mut contents = String::from("// Generated by build.rs. Do not edit.\n");
    contents.push_str(&format!(
        "#[allow(dead_code, unused_imports)]\n#[macro_use]\n#[path = {:?}]\npub mod common;\n\n",
        tests_dir.join("common/mod.rs")
    ));
    for perf_module in discover_perf_helper_modules(&tests_dir.join("perf")) {
        let module_name = format!("perf_{}", module_name_for_path(&perf_module));
        contents.push_str(&format!(
            "#[cfg(feature = \"gui\")]\n#[allow(dead_code, unused_imports)]\n#[path = {perf_module:?}]\npub(crate) mod {module_name};\n\n"
        ));
    }
    contents.push_str(&format!(
        "#[allow(dead_code, unused_imports)]\n#[path = {:?}]\npub(crate) mod support;\n\n",
        tests_dir.join("c_item_api/support.rs")
    ));
    contents.push_str(&format!(
        "#[allow(dead_code, unused_imports)]\n#[path = {:?}]\npub(crate) mod token_ui_fixtures;\n\n",
        tests_dir.join("common/token_ui_fixtures.rs")
    ));

    for file in module_files {
        let module_name = module_name_for_path(&file);
        contents.push_str(&format!(
            "#[allow(dead_code, unused_imports)]\n#[path = {file:?}]\nmod {module_name};\n\n"
        ));
    }

    std::fs::write(harness_path, contents).expect("write integration test harness");
}

#[derive(Debug)]
struct PreforkFullUiCase {
    attributes: Vec<String>,
    full_name: String,
    module_path: String,
    function_name: String,
    source_path: PathBuf,
}

#[derive(Debug)]
struct PreforkFullUiMarker {
    attributes: Vec<String>,
    function_name: String,
}

fn generate_prefork_full_ui_registry() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let tests_dir = manifest_dir.join("tests");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("out dir"));
    let registry_path = out_dir.join("prefork_full_ui_cases.rs");

    let source_files = discover_prefork_full_ui_sources(&tests_dir);
    let cases = collect_prefork_full_ui_cases(&tests_dir, source_files);
    let contents = render_prefork_full_ui_registry(cases);
    std::fs::write(registry_path, contents).expect("write prefork full-UI registry");
}

fn discover_prefork_full_ui_sources(tests_dir: &Path) -> Vec<PathBuf> {
    let top_level_sources = discover_top_level_test_modules(tests_dir);
    let mut sources = Vec::new();
    for source_path in top_level_sources {
        let module_directory = source_path.with_extension("");
        sources.push(source_path);
        if module_directory.is_dir() {
            sources.extend(discover_rust_sources(&module_directory));
        }
    }
    sources.sort();
    sources
}

fn discover_rust_sources(directory: &Path) -> Vec<PathBuf> {
    let mut sources = Vec::new();
    for entry in std::fs::read_dir(directory)
        .unwrap_or_else(|error| panic!("read {}: {error}", directory.display()))
    {
        let path = entry.expect("read test source entry").path();
        if path.is_dir() {
            sources.extend(discover_rust_sources(&path));
        } else if path.extension().and_then(|extension| extension.to_str()) == Some("rs") {
            sources.push(path);
        }
    }
    sources
}

fn collect_prefork_full_ui_cases(
    tests_dir: &Path,
    source_files: Vec<PathBuf>,
) -> Vec<PreforkFullUiCase> {
    let mut cases = Vec::new();
    let mut sources_by_case_name = BTreeMap::new();
    for source_path in source_files {
        println!("cargo:rerun-if-changed={}", source_path.display());
        let source = std::fs::read_to_string(&source_path)
            .unwrap_or_else(|error| panic!("read {}: {error}", source_path.display()));
        if !source.contains("prefork_full_ui_case") {
            continue;
        }
        let module_path = module_path_for_test_source(tests_dir, &source_path);
        for marker in parse_prefork_full_ui_markers(&source_path, &source) {
            let full_name = format!("{module_path}::{}", marker.function_name);
            reject_duplicate_prefork_case(&mut sources_by_case_name, &full_name, &source_path);
            cases.push(PreforkFullUiCase {
                attributes: marker.attributes,
                full_name,
                module_path: module_path.clone(),
                function_name: marker.function_name,
                source_path: source_path.clone(),
            });
        }
    }
    cases.sort_by(|left, right| left.full_name.cmp(&right.full_name));
    cases
}

fn reject_duplicate_prefork_case(
    sources_by_case_name: &mut BTreeMap<String, PathBuf>,
    full_name: &str,
    source_path: &Path,
) {
    let previous_path =
        sources_by_case_name.insert(full_name.to_string(), source_path.to_path_buf());
    if let Some(previous_path) = previous_path {
        panic!(
            "duplicate prefork full-UI case `{full_name}` in {} and {}",
            previous_path.display(),
            source_path.display()
        );
    }
}

fn render_prefork_full_ui_registry(cases: Vec<PreforkFullUiCase>) -> String {
    let mut contents = String::from("// Generated by build.rs. Do not edit.\n&[\n");
    for case in cases {
        for attribute in case.attributes {
            contents.push_str(&format!("    {attribute}\n"));
        }
        contents.push_str(&format!(
            "    Case::new({:?}, crate::{}::{}::run), // {}\n",
            case.full_name,
            case.module_path,
            case.function_name,
            case.source_path.display()
        ));
    }
    contents.push_str("]\n");
    contents
}

fn module_path_for_test_source(tests_dir: &Path, source_path: &Path) -> String {
    let relative_path = source_path
        .strip_prefix(tests_dir)
        .expect("test source should be under tests directory");
    let mut components: Vec<String> = relative_path
        .parent()
        .into_iter()
        .flat_map(Path::components)
        .map(|component| {
            component
                .as_os_str()
                .to_str()
                .expect("test module paths must be UTF-8")
                .to_string()
        })
        .collect();
    let stem = relative_path
        .file_stem()
        .and_then(|stem| stem.to_str())
        .expect("test source file stem must be UTF-8");
    if stem != "mod" {
        components.push(stem.to_string());
    }
    assert!(
        !components.is_empty(),
        "prefork marker cannot live in tests/mod.rs"
    );
    components.join("::")
}

fn parse_prefork_full_ui_markers(source_path: &Path, source: &str) -> Vec<PreforkFullUiMarker> {
    let file = syn::parse_file(source).unwrap_or_else(|error| {
        panic!(
            "parse candidate prefork full-UI source {}: {error}",
            source_path.display()
        )
    });

    file.items
        .into_iter()
        .filter_map(|item| match item {
            Item::Macro(item_macro) if is_prefork_full_ui_marker(&item_macro) => {
                Some(parse_prefork_full_ui_marker(source_path, item_macro))
            }
            _ => None,
        })
        .collect()
}

fn is_prefork_full_ui_marker(item_macro: &ItemMacro) -> bool {
    let path = &item_macro.mac.path;
    path.leading_colon.is_none()
        && path.segments.len() == 1
        && path.segments[0].ident == "prefork_full_ui_case"
        && matches!(path.segments[0].arguments, PathArguments::None)
}

fn parse_prefork_full_ui_marker(source_path: &Path, item_macro: ItemMacro) -> PreforkFullUiMarker {
    if !matches!(item_macro.mac.delimiter, MacroDelimiter::Brace(_)) {
        malformed_prefork_marker(source_path, "marker delimiter must be braces");
    }

    let function = syn::parse2::<ItemFn>(item_macro.mac.tokens).unwrap_or_else(|error| {
        malformed_prefork_marker(
            source_path,
            &format!("marker tokens must contain one function item: {error}"),
        )
    });
    validate_prefork_function(source_path, &function);

    PreforkFullUiMarker {
        attributes: item_macro
            .attrs
            .into_iter()
            .map(|attribute| attribute.to_token_stream().to_string())
            .collect(),
        function_name: function.sig.ident.to_string(),
    }
}

fn validate_prefork_function(source_path: &Path, function: &ItemFn) {
    validate_prefork_function_item(source_path, function);
    validate_prefork_signature(source_path, &function.sig);
    validate_prefork_parameter(source_path, &function.sig.inputs);
}

fn validate_prefork_function_item(source_path: &Path, function: &ItemFn) {
    if !function.attrs.is_empty() {
        malformed_prefork_marker(
            source_path,
            "function attributes must be placed on the marker invocation",
        );
    }
    if !matches!(function.vis, Visibility::Inherited) {
        malformed_prefork_marker(source_path, "function visibility must be inherited");
    }
}

fn validate_prefork_signature(source_path: &Path, signature: &syn::Signature) {
    if signature.constness.is_some()
        || signature.asyncness.is_some()
        || signature.unsafety.is_some()
        || signature.abi.is_some()
    {
        malformed_prefork_marker(
            source_path,
            "function must not be const, async, unsafe, or extern",
        );
    }
    if !signature.generics.params.is_empty() || signature.generics.where_clause.is_some() {
        malformed_prefork_marker(source_path, "function must not declare generics");
    }
    if !matches!(signature.output, ReturnType::Default) {
        malformed_prefork_marker(source_path, "function must not declare a return type");
    }
    if signature.variadic.is_some() {
        malformed_prefork_marker(source_path, "function must not be variadic");
    }
}

fn validate_prefork_parameter(
    source_path: &Path,
    inputs: &syn::punctuated::Punctuated<FnArg, syn::Token![,]>,
) {
    if inputs.len() != 1 {
        malformed_prefork_marker(
            source_path,
            "function must accept exactly one `env: &WowLuaEnv` parameter",
        );
    }

    let Some(FnArg::Typed(parameter)) = inputs.first() else {
        malformed_prefork_marker(source_path, "function must not have a receiver");
    };
    if !parameter.attrs.is_empty() {
        malformed_prefork_marker(source_path, "function parameter must not have attributes");
    }
    if !is_env_pattern(&parameter.pat) || !is_wow_lua_env_reference(&parameter.ty) {
        malformed_prefork_marker(
            source_path,
            "function parameter must be exactly `env: &WowLuaEnv`",
        );
    }
}

fn is_env_pattern(pattern: &Pat) -> bool {
    let Pat::Ident(pattern) = pattern else {
        return false;
    };
    pattern.ident == "env"
        && pattern.by_ref.is_none()
        && pattern.mutability.is_none()
        && pattern.subpat.is_none()
}

fn is_wow_lua_env_reference(ty: &Type) -> bool {
    let Type::Reference(reference) = ty else {
        return false;
    };
    if reference.lifetime.is_some() || reference.mutability.is_some() {
        return false;
    }

    let Type::Path(type_path) = reference.elem.as_ref() else {
        return false;
    };
    type_path.qself.is_none()
        && type_path.path.leading_colon.is_none()
        && type_path.path.segments.len() == 1
        && type_path.path.segments[0].ident == "WowLuaEnv"
        && matches!(type_path.path.segments[0].arguments, PathArguments::None)
}

fn malformed_prefork_marker(source_path: &Path, message: &str) -> ! {
    panic!(
        "malformed prefork_full_ui_case! marker in {}: {message}",
        source_path.display()
    )
}

fn discover_top_level_test_modules(tests_dir: &Path) -> Vec<PathBuf> {
    let entries = std::fs::read_dir(tests_dir).expect("read tests dir");
    entries
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("rs"))
        .filter(|path| should_include_in_integration_harness(path))
        .collect()
}

fn discover_perf_helper_modules(perf_dir: &Path) -> Vec<PathBuf> {
    let mut modules: Vec<_> = std::fs::read_dir(perf_dir)
        .expect("read perf test helper dir")
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("rs"))
        .collect();
    modules.sort();
    modules
}

fn should_include_in_integration_harness(path: &Path) -> bool {
    let Some(file_name) = path.file_name().and_then(|name| name.to_str()) else {
        return false;
    };
    !matches!(
        file_name,
        "blizzard_addon_closure_harness.rs"
            | "blizzard_addon_smoke_targets.rs"
            | "frame_positions.rs"
            | "integration.rs"
            | "mists_addonlist_interactions.rs"
            | "prefork_full_ui.rs"
            | "test_keybindings_panels_detail.rs"
    )
}

fn module_name_for_path(path: &Path) -> String {
    path.file_stem()
        .and_then(|stem| stem.to_str())
        .expect("test module stem")
        .to_string()
}
