//! Tests for global WoW API functions and pre-created global frames.
//!
//! Split into focused submodules:
//! - `global_functions` — pure utility globals (locale, build info, string
//!   helpers, hooksecurefunc, Mixin, presence checks).
//! - `frames_and_attributes` — UIParent, CreateFrame, CreateTexture, attribute
//!   propagation, table.unpack.
//! - `startup_globals` — value/return shape of legacy global functions
//!   (UnitPower, GetTime, ACTIONBAR_HOTKEY_FONT_COLOR, etc.).
//! - `startup_namespaces` — `C_*` namespace surfaces created during bootstrap.
//! - `runtime_subsystems` — text helpers, scroll scripts, C_Texture/atlas,
//!   animation runtime, gamepad cursor, unit state, popup/tooltip frames.

mod account_state_flags;
mod caa_constants;
mod combat_log_object;
mod frames_and_attributes;
mod global_functions;
mod housing_event_dispatch;
mod housing_result;
mod item_collection_secret_aspects;

macro_rules! active_retail_12_0_0_test_modules {
    ($($module:item)*) => {
        $(
            #[cfg(all(feature = "retail-12-0-0", not(feature = "retail-12-0-5")))]
            $module
        )*
    };
}

active_retail_12_0_0_test_modules! {
mod patch_12_0_0_adv_fly_cvar_values;
mod patch_12_0_0_audit_enums;
mod patch_12_0_0_changed_startup_values;
mod patch_12_0_0_char_customization_type_enums;
mod patch_12_0_0_charter_neighborhood_rename_error;
mod patch_12_0_0_chat_combat_audio_enums;
mod patch_12_0_0_combat_audio_party_percent_enums;
mod patch_12_0_0_combat_audio_percent_enums;
mod patch_12_0_0_combat_audio_player_cast_format_enums;
mod patch_12_0_0_combat_audio_player_health_format_enums;
mod patch_12_0_0_combat_audio_player_resource_format_enums;
mod patch_12_0_0_combat_audio_say_if_targeted_enums;
mod patch_12_0_0_combat_audio_spec_setting_enums;
mod patch_12_0_0_combat_audio_target_cast_format_enums;
mod patch_12_0_0_combat_audio_target_death_behavior_enums;
mod patch_12_0_0_combat_audio_target_health_format_enums;
mod patch_12_0_0_combat_audio_throttle_enums;
mod patch_12_0_0_combat_audio_type_enums;
mod patch_12_0_0_combat_audio_unit_enums;
mod patch_12_0_0_combat_log_message_order_enums;
mod patch_12_0_0_constants;
mod patch_12_0_0_cooldown_housing_enums;
mod patch_12_0_0_cooldown_viewer_alert_type_enums;
mod patch_12_0_0_crafting_order_item_flags_enums;
mod patch_12_0_0_crafting_order_item_type_enums;
mod patch_12_0_0_crafting_order_result_changed_enums;
mod patch_12_0_0_crafting_order_result_enums;
mod patch_12_0_0_cvar_removals;
mod patch_12_0_0_damage_meter_numbers_enums;
mod patch_12_0_0_damage_meter_override_type_enums;
mod patch_12_0_0_damage_meter_session_type_enums;
mod patch_12_0_0_damage_meter_spell_details_display_type_enums;
mod patch_12_0_0_damage_meter_storage_type_enums;
mod patch_12_0_0_damage_meter_type_enums;
mod patch_12_0_0_damage_meter_visibility_enums;
mod patch_12_0_0_dungeon_encounter_creature_flags_enums;
mod patch_12_0_0_dungeon_encounter_flags_enums;
mod patch_12_0_0_dungeon_encounter_trigger_type_enums;
mod patch_12_0_0_duration_time_modifier_enums;
mod patch_12_0_0_edit_mode_account_aura_settings_enums;
mod patch_12_0_0_edit_mode_damage_meter_settings_enums;
mod patch_12_0_0_edit_mode_encounter_events_settings_enums;
mod patch_12_0_0_edit_mode_personal_resource_display_settings_enums;
mod patch_12_0_0_edit_mode_system_enums;
mod patch_12_0_0_edit_mode_unit_frame_settings_enums;
mod patch_12_0_0_encounter_event_cast_state_enums;
mod patch_12_0_0_encounter_event_iconmask_enums;
mod patch_12_0_0_encounter_event_severity_enums;
mod patch_12_0_0_encounter_events_icon_direction_enums;
mod patch_12_0_0_encounter_events_orientation_enums;
mod patch_12_0_0_encounter_events_visibility_enums;
mod patch_12_0_0_encounter_timeline_event_sort_direction_enums;
mod patch_12_0_0_encounter_timeline_event_source_enums;
mod patch_12_0_0_encounter_timeline_event_state_enums;
mod patch_12_0_0_encounter_timeline_icon_set_enums;
mod patch_12_0_0_encounter_timeline_track_enums;
mod patch_12_0_0_encounter_timeline_track_type_enums;
mod patch_12_0_0_expansion_landing_page_type_removals;
mod patch_12_0_0_expansion_level_enums;
mod patch_12_0_0_font_string_scale_animation_mode_enums;
mod patch_12_0_0_fragment_id_enums;
mod patch_12_0_0_frame_tutorial_account_transmog_enums;
mod patch_12_0_0_guild_neighborhood_error_constants;
mod patch_12_0_0_guild_neighborhood_rename_error;
mod patch_12_0_0_housing_catalog_entry_info;
mod patch_12_0_0_housing_catalog_entry_subtype_enums;
mod patch_12_0_0_housing_decor_placement_restriction_enums;
mod patch_12_0_0_housing_favor_update_source_enums;
mod patch_12_0_0_housing_favor_update_type_enums;
mod patch_12_0_0_housing_recent_ally_error_constants;
mod patch_12_0_0_housing_room_component_flags_enums;
mod patch_12_0_0_initiative_flags_enums;
mod patch_12_0_0_item_creation_context_additions;
mod patch_12_0_0_item_creation_context_removals;
mod patch_12_0_0_lfg_entry_general_playstyle_enums;
mod patch_12_0_0_limited_input_type_enums;
mod patch_12_0_0_lua_curve_type_enums;
mod patch_12_0_0_mount_journal_nameplate_cvar_values;
mod patch_12_0_0_nameplate_cast_bar_display_enums;
mod patch_12_0_0_nameplate_cvar_changed_values;
mod patch_12_0_0_nameplate_enemy_npc_aura_display_enums;
mod patch_12_0_0_nameplate_enemy_player_aura_display_enums;
mod patch_12_0_0_nameplate_friendly_player_aura_display_enums;
mod patch_12_0_0_nameplate_info_display_enums;
mod patch_12_0_0_nameplate_simplified_type_enums;
mod patch_12_0_0_nameplate_size_enums;
mod patch_12_0_0_nameplate_stack_type_enums;
mod patch_12_0_0_nameplate_style_enums;
mod patch_12_0_0_nameplate_threat_display_enums;
mod patch_12_0_0_nameplate_type_enums;
mod patch_12_0_0_neighborhood_initiative_chest_result_enums;
mod patch_12_0_0_neighborhood_initiative_flags_enums;
mod patch_12_0_0_neighborhood_initiative_neighborhood_types_enums;
mod patch_12_0_0_neighborhood_initiative_task_type_enums;
mod patch_12_0_0_neighborhood_initiative_update_status_enums;
mod patch_12_0_0_neighborhood_initiatives_completion_states_enums;
mod patch_12_0_0_npc_crafting_order_set_flags_enums;
mod patch_12_0_0_pet_journal_overlay_tracker_cvar_values;
mod patch_12_0_0_player_companion_info_flags_enums;
mod patch_12_0_0_prey_hunt_progress_state_enums;
mod patch_12_0_0_procedural_spawn_interaction_mode_enums;
mod patch_12_0_0_procedural_spawn_volume_chunk_flags_enums;
mod patch_12_0_0_raid_aura_organization_type_enums;
mod patch_12_0_0_raid_dispel_display_type_enums;
mod patch_12_0_0_rco_close_reason_enums;
mod patch_12_0_0_removed_global_constants;
mod patch_12_0_0_renown_reward_display_type_enums;
mod patch_12_0_0_renown_rewards_flags_enums;
mod patch_12_0_0_secrecy_level_enums;
mod patch_12_0_0_send_addon_message_result_enums;
mod patch_12_0_0_simple_order_status_enums;
mod patch_12_0_0_sleeves_geo_range_enums;
mod patch_12_0_0_small_enums;
mod patch_12_0_0_spell_aura_visibility_type_enums;
mod patch_12_0_0_spell_diminish_category_enums;
mod patch_12_0_0_spell_diminish_ruleset_enums;
mod patch_12_0_0_status_bar_fill_style_enums;
mod patch_12_0_0_status_bar_interpolation_enums;
mod patch_12_0_0_status_bar_timer_direction_enums;
mod patch_12_0_0_table_security_option_enums;
mod patch_12_0_0_tooltip_data_line_type_enums;
mod patch_12_0_0_trait_node_entry_type_enums;
mod patch_12_0_0_transmog_outfit_data_flags_enums;
mod patch_12_0_0_transmog_outfit_display_type_enums;
mod patch_12_0_0_transmog_outfit_entry_flags_enums;
mod patch_12_0_0_transmog_outfit_entry_source_enums;
mod patch_12_0_0_transmog_outfit_equip_action_enums;
mod patch_12_0_0_transmog_outfit_set_type_enums;
mod patch_12_0_0_transmog_outfit_slot_error_metadata_enums;
mod patch_12_0_0_transmog_outfit_slot_flags_enums;
mod patch_12_0_0_transmog_outfit_slot_metadata_enums;
mod patch_12_0_0_transmog_outfit_slot_option_flags_enums;
mod patch_12_0_0_transmog_outfit_slot_option_metadata_enums;
mod patch_12_0_0_transmog_outfit_slot_position_enums;
mod patch_12_0_0_transmog_outfit_slot_save_flags_enums;
mod patch_12_0_0_transmog_outfit_slot_warning_enums;
mod patch_12_0_0_transmog_outfit_transaction_enums;
mod patch_12_0_0_transmog_situation_enums;
mod patch_12_0_0_ui_covenant_display_info_flags_enums;
mod patch_12_0_0_ui_enum_metadata;
mod patch_12_0_0_unit_aura_sort_direction_enums;
mod patch_12_0_0_unit_aura_sort_rule_big_defensive;
mod patch_12_0_0_unit_power_spell_ids;
}

mod patch_12_0_7_edit_mode_enum_values;
mod patch_12_1_service_payloads;
mod runtime_subsystems;
mod startup_globals;
mod startup_namespaces;
mod transmog_outfit_enums;
mod transmog_situation;
