//! Enum constant data for WoW API.
//!
//! This module contains only DATA - static arrays of enum values.
//! The registration logic is in enum_api.rs.

mod addon_system;
mod combat_system;
mod edit_mode;
mod game_system;
mod widget;

pub use addon_system::*;
pub use combat_system::*;
pub use edit_mode::*;
pub use game_system::*;
pub use widget::*;

/// Enum definition: (enum_name, &[(variant_name, value)])
pub type EnumDef = (&'static str, &'static [(&'static str, i32)]);

/// Sequential enum: (enum_name, &[variant_names]) - values are 0, 1, 2, ...
pub type SeqEnumDef = (&'static str, &'static [&'static str]);

// ============================================================================
// All sequential enums (for batch registration)
// ============================================================================

pub const SEQUENTIAL_ENUMS: &[SeqEnumDef] = &[
    SCRIPTED_ANIMATION_TRAJECTORY,
    UI_WIDGET_TOOLTIP_LOCATION,
    UI_WIDGET_SCALE,
    WIDGET_REWARD_SHOWN_STATE,
    SPELL_DISPLAY_BORDER_COLOR,
    STATUS_BAR_COLOR_TINT_VALUE,
    STATUS_BAR_OVERRIDE_TEXT_SHOWN,
    STATUS_BAR_VALUE_TEXT_TYPE,
    WIDGET_ANIMATION_TYPE,
    WIDGET_SHOW_GLOW_STATE,
    ICON_AND_TEXT_WIDGET_STATE,
    ZONE_CONTROL_STATE,
    ZONE_CONTROL_FILL_TYPE,
    CAPTURE_BAR_FILL_DIRECTION,
    UI_WIDGET_TEXTURE_TEXT_SIZE,
    MAP_PIN_ANIMATION_TYPE,
    UI_WIDGET_FONT_TYPE,
    UI_WIDGET_BUTTON_ICON_TYPE,
    UI_WIDGET_MODEL_SCENE_LAYER,
    SCREEN_LOCATION_TYPE,
    START_TIMER_TYPE,
    QUEST_SESSION_RESULT,
    REPUTATION_SORT_TYPE,
    QUEST_COMPLETE_SPELL_TYPE,
    BANK_LOCKED_REASON,
    QUEST_SESSION_COMMAND,
    EVENT_TOAST_DISPLAY_TYPE,
    SEND_REPORT_RESULT,
    EDIT_MODE_PRESET_LAYOUTS,
    BAGS_ORIENTATION,
    COLOR_OVERRIDE,
    CLUB_STREAM_TYPE,
    RECRUIT_A_FRIEND_REWARDS_VERSION,
    CLICK_BINDING_TYPE,
    CUSTOM_BINDING_TYPE,
    CALENDAR_EVENT_TYPE,
    CAMERA_MODE_ASPECT_RATIO,
    CALENDAR_STATUS,
    ACTION_BAR_ORIENTATION,
    WIDGET_OPACITY_TYPE,
    EDIT_MODE_ACTION_BAR_SETTING,
    GARR_AUTO_MISSION_EVENT_TYPE,
    CLUB_MEMBER_PRESENCE,
    ACTION_BAR_VISIBLE_SETTING,
    EDIT_MODE_SYSTEM,
    EDIT_MODE_CHAT_FRAME_SETTING,
    EDIT_MODE_ACCOUNT_SETTING,
    EDIT_MODE_LAYOUT_TYPE,
    #[cfg(feature = "retail-12-1-0")]
    EDIT_MODE_LOSS_OF_CONTROL_SETTING,
    EDIT_MODE_UNIT_FRAME_SETTING,
    EDIT_MODE_CAST_BAR_SETTING,
    EDIT_MODE_MINIMAP_SETTING,
    EDIT_MODE_AURA_FRAME_SETTING,
    EDIT_MODE_BAGS_SETTING,
    EDIT_MODE_MICRO_MENU_SETTING,
    EDIT_MODE_OBJECTIVE_TRACKER_SETTING,
    EDIT_MODE_STATUS_TRACKING_BAR_SETTING,
    EDIT_MODE_DURABILITY_FRAME_SETTING,
    EDIT_MODE_TIMER_BARS_SETTING,
    EDIT_MODE_VEHICLE_SEAT_INDICATOR_SETTING,
    EDIT_MODE_ARCHAEOLOGY_BAR_SETTING,
    EDIT_MODE_COOLDOWN_VIEWER_SETTING,
    EDIT_MODE_PERSONAL_RESOURCE_DISPLAY_SETTING,
    PERSONAL_RESOURCE_DISPLAY_VISIBLE_SETTING,
    ENCOUNTER_EVENTS_VIEW_TYPE,
    ENCOUNTER_EVENTS_ORIENTATION,
    ENCOUNTER_EVENTS_VISIBILITY,
    ENCOUNTER_EVENTS_TOOLTIP_ANCHOR,
    EDIT_MODE_DAMAGE_METER_SETTING,
    DAMAGE_METER_STYLE,
    DAMAGE_METER_NUMBERS,
    DAMAGE_METER_VISIBILITY,
    DAMAGE_METER_SOURCE_DISPLAY_TYPE,
    RAID_AURA_ORGANIZATION_TYPE,
    AURA_FRAME_VISIBLE_SETTING,
    EDIT_MODE_SETTING_DISPLAY_TYPE,
    AURA_FRAME_ORIENTATION,
    MICRO_MENU_ORDER,
    MICRO_MENU_ORIENTATION,
    RAID_GROUP_DISPLAY_TYPE,
    SORT_PLAYERS_BY,
    VIEW_ARENA_SIZE,
    VIEW_RAID_SIZE,
    COOLDOWN_VIEWER_BAR_CONTENT,
    COOLDOWN_VIEWER_ICON_DIRECTION,
    COOLDOWN_VIEWER_ORIENTATION,
    COOLDOWN_VIEWER_VISIBLE_SETTING,
    CONTENT_TRACKING_TYPE,
    RELATIVE_CONTENT_DIFFICULTY,
    CLUB_TYPE,
    CLUB_FINDER_SETTING_FLAGS,
    CLUB_ACTION_TYPE,
    MATCH_DETAIL_TYPE,
    PVP_UNIT_CLASSIFICATION,
    ARROW_CALLOUT_DIRECTION,
    NAVIGATION_STATE,
    UI_FRAME_TYPE,
    COOLDOWN_VIEWER_CATEGORY,
    #[cfg(feature = "retail-12-1-0")]
    COOLDOWN_VIEWER_SOUND,
    #[cfg(feature = "retail-12-1-0")]
    CUSTOM_AURA_BUTTON_DISPEL_TYPE_TEXTURE_STYLE,
    #[cfg(feature = "retail-12-1-0")]
    RECENT_ALLIES_FRIEND_TAG,
    #[cfg(feature = "retail-12-1-0")]
    SOCIAL_SYSTEM_TYPE,
    TTS_VOICE_TYPE,
    GUILD_ERROR_TYPE,
    ROLODEX_TYPE,
    INVALID_PLOT_SCREENSHOT_REASON,
    PING_RESULT,
    VOICE_CHAT_STATUS_CODE,
    TRAIT_NODE_TYPE,
    TRAIT_NODE_ENTRY_TYPE,
    TRAIT_DEFINITION_SUB_TYPE,
    ACCOUNT_CURRENCY_TRANSFER_RESULT,
    CURRENCY_FILTER_TYPE,
    END_OF_MATCH_TYPE,
    SUPER_TRACKING_TYPE,
    SUPER_TRACKING_MAP_PIN_TYPE,
    TRAIT_EDGE_VISUAL_STYLE,
    NEIGHBORHOOD_OWNER_TYPE,
    HOUSING_LAYOUT_RESTRICTION,
    HOUSING_EXPERT_SUBMODE_RESTRICTION,
    #[cfg(feature = "retail-12-1-0")]
    HOUSING_RESULT,
    #[cfg(feature = "retail-12-1-0")]
    HOUSING_PET_BEHAVIOR_TYPE,
    #[cfg(feature = "retail-12-1-0")]
    HOUSE_EDITOR_PLAYER_TYPE,
    #[cfg(feature = "retail-12-1-0")]
    HOUSING_BLUEPRINT_TYPE,
    #[cfg(feature = "retail-12-1-0")]
    HOUSING_BLUEPRINT_CONTENT_TYPE,
    SPELL_BOOK_SPELL_BANK,
    SPELL_BOOK_ITEM_TYPE,
    BATTLE_PET_ACTION,
    COMPANION_CONFIG_SLOT_TYPES,
    // Combat / encounter / damage meter enums
    COMBAT_AUDIO_ALERT_TYPE,
    COMBAT_AUDIO_ALERT_THROTTLE,
    COMBAT_AUDIO_ALERT_UNIT,
    DAMAGE_METER_SESSION_TYPE,
    DAMAGE_METER_TYPE,
    ENCOUNTER_TIMELINE_TRACK,
    ENCOUNTER_TIMELINE_EVENT_STATE,
    ENCOUNTER_EVENT_SEVERITY,
    SPELL_AURA_VISIBILITY_TYPE,
    PREY_HUNT_PROGRESS_STATE,
    STATUS_BAR_FILL_STYLE,
    RAID_DISPEL_DISPLAY_TYPE,
    #[cfg(feature = "retail-12-1-0")]
    RAID_DISPEL_OVERLAY_TYPE,
    NAME_PLATE_STYLE,
    AUTO_COMPLETE_PRIORITY,
];

// All explicit value enums (for batch registration)
pub const EXPLICIT_ENUMS: &[EnumDef] = &[
    #[cfg(feature = "retail-12-1-0")]
    COOLDOWN_VIEWER_SOUND_META,
    #[cfg(feature = "retail-12-1-0")]
    CUSTOM_AURA_BUTTON_DISPEL_TYPE_TEXTURE_STYLE_META,
    #[cfg(feature = "retail-12-1-0")]
    RECENT_ALLIES_FRIEND_TAG_META,
    #[cfg(feature = "retail-12-1-0")]
    ROLODEX_TYPE_LEGACY_FRIEND,
    #[cfg(feature = "retail-12-1-0")]
    ROLODEX_TYPE_META,
    #[cfg(feature = "retail-12-1-0")]
    BATTLE_NET_FRIEND_LEVEL,
    #[cfg(feature = "retail-12-1-0")]
    BATTLE_NET_FRIEND_LEVEL_META,
    #[cfg(feature = "retail-12-1-0")]
    BATTLE_NET_FRIEND_TAG,
    #[cfg(feature = "retail-12-1-0")]
    BATTLE_NET_FRIEND_TAG_META,
    #[cfg(feature = "retail-12-1-0")]
    SOCIAL_UI_BLOCK_TYPE,
    #[cfg(feature = "retail-12-1-0")]
    SOCIAL_UI_BLOCK_TYPE_META,
    #[cfg(feature = "retail-12-1-0")]
    SOCIAL_UI_PRESENCE_TYPE,
    #[cfg(feature = "retail-12-1-0")]
    SOCIAL_UI_PRESENCE_TYPE_META,
    #[cfg(feature = "retail-12-1-0")]
    SOCIAL_SYSTEM_TYPE_META,
    #[cfg(feature = "retail-12-1-0")]
    EDIT_MODE_ACCOUNT_SETTING_META,
    #[cfg(feature = "retail-12-1-0")]
    EDIT_MODE_LOSS_OF_CONTROL_SETTING_META,
    #[cfg(feature = "retail-12-1-0")]
    EDIT_MODE_SYSTEM_META,
    #[cfg(feature = "retail-12-1-0")]
    VISUAL_ALERT_TYPE,
    #[cfg(feature = "retail-12-1-0")]
    VISUAL_ALERT_TYPE_META,
    #[cfg(feature = "retail-12-1-0")]
    RAID_DISPEL_OVERLAY_TYPE_META,
    #[cfg(feature = "retail-12-1-0")]
    HOUSING_RESULT_META,
    #[cfg(feature = "retail-12-1-0")]
    HOUSING_PET_BEHAVIOR_TYPE_META,
    #[cfg(feature = "retail-12-1-0")]
    HOUSE_EDITOR_PLAYER_TYPE_META,
    #[cfg(feature = "retail-12-1-0")]
    HOUSE_SETTING_FLAGS,
    #[cfg(feature = "retail-12-1-0")]
    HOUSE_SETTING_FLAGS_META,
    #[cfg(feature = "retail-12-1-0")]
    HOUSING_BUDGET_TYPE,
    #[cfg(feature = "retail-12-1-0")]
    HOUSING_BUDGET_TYPE_META,
    #[cfg(feature = "retail-12-1-0")]
    HOUSING_HOUSE_SCOPE,
    #[cfg(feature = "retail-12-1-0")]
    HOUSING_HOUSE_SCOPE_META,
    #[cfg(feature = "retail-12-1-0")]
    HOUSING_BLUEPRINT_TYPE_META,
    #[cfg(feature = "retail-12-1-0")]
    HOUSING_BLUEPRINT_CONTENT_TYPE_META,
    #[cfg(feature = "retail-12-1-0")]
    HOUSING_BLUEPRINT_UNMET_REQUIREMENT_FLAGS,
    #[cfg(feature = "retail-12-1-0")]
    HOUSING_BLUEPRINT_UNMET_REQUIREMENT_FLAGS_META,
    LFG_ROLE,
    UNIT_SEX,
    UI_WIDGET_TEXT_SIZE_TYPE,
    WIDGET_TEXT_HORIZONTAL_ALIGNMENT,
    BAG_INDEX,
    EDIT_MODE_ACTION_BAR_SYSTEM_INDICES,
    MINIMAP_TRACKING_FILTER,
    BAG_SLOT_FLAGS,
    GARRISON_FOLLOWER_TYPE,
    GARRISON_TYPE,
    EDIT_MODE_UNIT_FRAME_SYSTEM_INDICES,
    EDIT_MODE_AURA_FRAME_SYSTEM_INDICES,
    EDIT_MODE_STATUS_TRACKING_BAR_SYSTEM_INDICES,
    EDIT_MODE_COOLDOWN_VIEWER_SYSTEM_INDICES,
    EDIT_MODE_ENCOUNTER_EVENTS_SYSTEM_INDICES,
    EDIT_MODE_ENCOUNTER_EVENTS_SETTING,
    ENCOUNTER_EVENTS_ICON_DIRECTION,
    AURA_FRAME_ICON_DIRECTION,
    AURA_FRAME_ICON_WRAP,
    BAGS_DIRECTION,
    CLUB_FINDER_REQUEST_TYPE,
    MAP_CANVAS_POSITION,
    VIGNETTE_OBJECTIVE_TYPE,
    HOUSING_PLOT_OWNER_TYPE,
    PARTY_PLAYLIST_ENTRY,
    CHAT_CHANNEL_TYPE,
    PVP_MATCH_STATE,
    HOUSING_FIXTURE_DECOR_ACTION,
    #[cfg(feature = "retail-12-1-0")]
    TIERED_ENTRANCE_TYPE,
    TIERED_ENTRANCE_REWARD_TYPE,
    EDIT_MODE_CHAT_FRAME_DISPLAY_ONLY_SETTING,
    GUIDE_FRAME_STATE,
    WARBAND_SCENE_ANIMATION_EVENT,
    WORLD_ELAPSED_TIMER_TYPES,
    CURIO_RARITY,
    CLUB_ROLE_IDENTIFIER,
    CLUB_REMOVED_REASON,
    SPELL_BOOK_SKILL_LINE_INDEX,
    ACCOUNT_STORE_CATEGORY_TYPE,
    AUTO_COMPLETE_ENTRY_FLAG,
    WORLD_TIER_DIFFICULTY,
    // Combat system explicit enums (bitmask values)
    COMBAT_AUDIO_ALERT_PARTY_PERCENT_VALUES_META,
    COMBAT_AUDIO_ALERT_PLAYER_CAST_FORMAT_VALUES_META,
    COMBAT_AUDIO_ALERT_PLAYER_HEALTH_FORMAT_VALUES_META,
    COMBAT_AUDIO_ALERT_SAY_IF_TARGETED_TYPE_META,
    COMBAT_AUDIO_ALERT_TARGET_CAST_FORMAT_VALUES_META,
    COMBAT_AUDIO_ALERT_TARGET_DEATH_BEHAVIOR_META,
    COMBAT_AUDIO_ALERT_TARGET_HEALTH_FORMAT_VALUES_META,
    COMBAT_AUDIO_ALERT_DEBUFF_SELF_ALERT_VALUES_META,
    COMBAT_AUDIO_ALERT_PLAYER_DEBUFF_FORMAT_VALUES_META,
    NAME_PLATE_SIZE,
    DAMAGE_METER_VISIBILITY_META,
    EVENT_REALM_QUEUES,
    GAME_MODE,
    PLAYER_MENTORSHIP_STATUS,
    CHARACTER_CREATE_TYPE,
    VALUE_ADDED_SERVICE_TYPE,
    #[cfg(feature = "retail-12-1-0")]
    FORBIDDEN_ASPECT,
    #[cfg(feature = "retail-12-1-0")]
    FORBIDDEN_ASPECT_META,
    CREATION_CLASS_DISABLED_REASON,
    CREATION_RACE_DISABLED_REASON,
    VAS_QUEUE_STATUS,
];
